### ISSUE TITLE
translate false option hides non default language values

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-boost#16]
> Hello,
> 
> I've been experimenting a weird behaviour likely related to this and #6
> 
> Basically, fields with the `translate: false` option stop displaying values in the translated page. This is an issue in the website as well as in the panel, where the fields with the `translate: false` options appear empty. Since these fields are also required, this basically blocks editors from saving pages in the translated versions...
> 
> When I set to `debug: false;`, the problem dissappear. Also, when I set `'bnomei.boost.cache' => false`, the problem also stops. So I guess it must be from the cache?
> 
> Of course, not using the translate: false option could solve the issue, as well as making a page model that would overwrite the field values that should not be translated (since they would then be hard-coded within the content files). So far I set off the _boost_ cache, but I'm unsure this should be the best long-term solution as I do see very pleasant performance gains by using the (sqlite) cache!
> 
> I've seen a _wontfix_ tag on #6 and was curious about the issue, is there a lot of complexity into making this work with translate: false? I guess it's another layer of complexity on top?

_Originally posted by @francois-gm in https://github.com/bnomei/kirby3-boost/issues/11#issuecomment-1292636309_

**Comment by francois-gm** [comment]
Thanks, updated and it works :)
