### ISSUE TITLE
Project Website Fails to Load

### ISSUE THREAD

**Issue by luismqueral** [bnomei/kirby3-boost#17]
Hey there, just a heads up that your website for this project is down 😬.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/3460146/204000839-4e920f41-d026-4884-9cc9-1d73200e870a.png">

**Comment by bnomei** [comment]
thanks. will get it sorted asap.

**Comment by luismqueral** [comment]
Cool! Thanks for all of your hard work, looking forward to using this plugin.
