### ISSUE TITLE
PHP 8.1 and xxHash Hash issue 

### ISSUE THREAD

**Issue by psntr** [bnomei/kirby3-boost#18]
Hey there,

I'm running Boost on some server that, at the moment, and for some odd reasons, do not provide PHP 8.1. I'm wondering if there is an option to switch the hashing algo to something that PHP 8.0 can support?

It's a bit a drawback considering the performance advantage of the new hashing features, but at this stage, I can't migrate to another server.

**Comment by bnomei** [comment]
closed in v2.2.0

**Comment by psntr** [comment]
Thank you for the reactivity!
