### ISSUE TITLE
Bolt error

### ISSUE THREAD

**Issue by saschabregenhorn** [bnomei/kirby3-boost#20]
Hey,

I just tried the [basic setup](https://github.com/bnomei/kirby3-boost#setup) for the Default Template (Kirby 3.9.4 / PHP 8.1.13) and get this error:

`Bnomei\Bolt::page(): Argument #1 ($id) must be of type string, null given, called in /site/plugins/kirby3-boost/classes/Bolt.php on line 233`

Any ideas what I am doing wrong? Thanks!

**Comment by bnomei** [comment]
you did nothing wrong. my helper that scans for all folders had a bug.

**Comment by saschabregenhorn** [comment]
> you did nothing wrong. my helper that scans for all folders had a bug.

Thanks for the quick replay, works!
