### ISSUE TITLE
All the demo pages throw errors

### ISSUE THREAD

**Issue by trych** [bnomei/kirby3-boost#9]
Hi there,
it seems I cannot run any of the demo pages right now, they all show an error message.

Would be cool if this could be fixed, without the demo pages I am somewhat lost on what to expect. :)

Thanks!
trych

**Comment by bnomei** [comment]
Thanks for letting me know. My demo site has seen quiet a few hacking attempts since i put them up. Seems like i missed a DDoS attack warning and Nginx PHP ran out of memory. It is up and running again.

**Comment by trych** [comment]
Thanks a lot!
